export enum ImportRequestType {
  MATERIAL_BY_PO = 'MATERIAL_BY_PO',
  MATERIAL_RETURN = 'MATERIAL_RETURN',
  MATERIAL_NOT_BY_PO = 'MATERIAL_NOT_BY_PO',
  PRODUCT_BY_BATCH = 'PRODUCT_BY_BATCH',
  PRODUCT_RETURN = 'PRODUCT_RETURN',
  PRODUCT_NOT_BY_BATCH = 'PRODUCT_NOT_BY_BATCH',
}
